# Generated by Django 4.0.6 on 2022-07-27 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_olx', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='data_string',
            field=models.TextField(null=True, verbose_name='Конвертовані дані'),
        ),
    ]
