# Generated by Django 4.0.6 on 2022-07-27 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parser_olx', '0003_alter_category_data_string'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='data_string',
        ),
    ]
