# Generated by Django 4.0.6 on 2022-07-27 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parser_olx', '0005_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
