# Generated by Django 4.0.6 on 2022-07-27 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_olx', '0007_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Ціна'),
        ),
    ]
